### ISSUE TITLE
Rename `Thread` table to `Mission` and `Response` table to `Module_data`

### ISSUE THREAD

**Issue by thibaud-perrin** [DigitalKin-ai/kin-kernel#44]
### 📝 Issue Description

Rename the `Thread` table to `Mission` table, and refactor its fields.
Rename the `Response` table to `Module_data` table, and refactor its fields.

### 🚀 Objective

The objective of this issue is to improve the clarity and maintainability of the database schema by renaming the tables and refactoring their fields to better reflect their purpose and usage.

### 🐞 Steps to Reproduce

1. Go to the database schema.
2. Locate the `Thread` and `Response` tables.
3. Observe the current names and fields of these tables.

### 💰 Business Impact

Renaming and refactoring these tables will enhance the readability and maintainability of the database schema, which can lead to improved development efficiency and reduced errors in the long term.

### 📝 Task List

- [ ] Rename the `Thread` table to `Mission`.
- [ ] Refactor the fields in the `Mission` table.
- [ ] Rename the `Response` table to `Module_data`.
- [ ] Refactor the fields in the `Module_data` table.
- [ ] Update all references to these tables in the codebase.

### 💡 Potential Solution

To resolve this issue, we need to:
1. Execute SurrealQL commands to rename the tables.
2. Modify the schema definitions to update the fields.
3. Update the application code to reflect these changes.

### 📈 Priority

High 🚨

**Comment by thibaud-perrin** [comment]
## Missions schema:

```sql
DEFINE TABLE IF NOT EXISTS missions SCHEMAFULL;
DEFINE FIELD organization ON missions TYPE record ASSERT $value != NONE;
DEFINE FIELD user ON missions TYPE record ASSERT $value != NONE;
DEFINE FIELD setup ON missions TYPE record ASSERT $value != NONE;
DEFINE FIELD logs ON missions TYPE array<record<module_data>> DEFAULT [];
DEFINE FIELD outputs ON missions TYPE array<record<module_data>> DEFAULT [];
DEFINE FIELD views ON missions TYPE array<record<module_data>> DEFAULT [];
DEFINE FIELD cache ON missions TYPE array<record<module_data>> DEFAULT [];
DEFINE FIELD creation_date ON missions TYPE datetime ASSERT $value != NONE VALUE $before or time::now() DEFAULT time::now() READONLY;
```
## Module Data schema:
```sql
DEFINE TABLE IF NOT EXISTS module_data SCHEMAFULL;
DEFINE FIELD module ON module_data TYPE record<modules> ASSERT $value != NONE;
DEFINE FIELD mission ON module_data TYPE record<missions> ASSERT $value != NONE;
DEFINE FIELD content ON module_data FLEXIBLE TYPE object;
DEFINE FIELD usage ON module_data FLEXIBLE TYPE object;
DEFINE FIELD IF NOT EXISTS data_type ON module_data TYPE string  ASSERT $value INSIDE ['logs', 'outputs', 'views', 'caches'];
DEFINE FIELD creation_date ON missions TYPE datetime ASSERT $value != NONE VALUE $before or time::now() DEFAULT time::now() READONLY;
```
